server:
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.55.2:1521/ORCL21PDB1
    username: MYUSER
    password: ${DB_PASSWORD:12345}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update  # C? th? ??i th?nh validate n?u kh?ng mu?n t? ??ng s?a DB
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Hi?n th? SQL r? r?ng h?n trong log